# Generated by Django 5.2.4 on 2026-02-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationtopic",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
