# Generated by Django 6.1 on 2026-09-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_usertopicsubscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(help_text='Markdown content.')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='subscriptions.notificationtopic')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
