FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --shell /bin/bash appuser

ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf8 \
    PYTHONUTF8=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DJANGO_SETTINGS_MODULE=src.settings.docker_prod

ARG PROJECT_SLUG
ARG PROJECT_NAME
ARG PROJECT_DESCRIPTION
ARG PROJECT_DOMAIN
ARG DJANGO_SECRET_KEY
ARG DJANGO_ALLOWED_HOSTS

WORKDIR /app

COPY pyproject.toml uv.lock ./

RUN pip install --no-cache-dir uv && \
    uv sync --group docker && \
    chmod -R a+r /app/.venv

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

COPY . .

RUN mkdir -p /app/data && chown appuser:appuser /app/data

RUN chmod +x /usr/local/bin/entrypoint.sh && chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

ENTRYPOINT ["entrypoint.sh"]
