FROM python:3.14-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/* \
    && useradd --create-home --shell /bin/bash appuser

ENV PYTHONUNBUFFERED=1 \
    PYTHONIOENCODING=utf8 \
    PYTHONUTF8=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    DJANGO_SETTINGS_MODULE=src.settings.production

ARG PIP_DISABLE_PIP_VERSION_CHECK=1
ARG PIP_NO_CACHE_DIR=1

ARG PROJECT_SLUG
ARG PROJECT_NAME
ARG PROJECT_DESCRIPTION
ARG PROJECT_DOMAIN
ARG DJANGO_SECRET_KEY
ARG DJANGO_ALLOWED_HOSTS

WORKDIR /app

COPY pyproject.toml ./pyproject.toml

RUN pip install --no-cache-dir --group production

COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh

COPY . .

RUN mkdir -p /app/data && chown appuser:appuser /app/data

RUN chmod +x /usr/local/bin/entrypoint.sh && chown -R appuser:appuser /app

USER appuser

EXPOSE 8000

ENTRYPOINT ["entrypoint.sh"]
