name: ${PROJECT_SLUG}-prod

services:
  django_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        PROJECT_SLUG: ${PROJECT_SLUG}
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_DESCRIPTION: ${PROJECT_DESCRIPTION}
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    image: ${PROJECT_SLUG}:prod
    container_name: ${PROJECT_SLUG}-prod
    env_file: .env
    ports:
      - "${PROJECT_PORT_PROD:-8000}:8000"
    volumes:
      - prod_data:/app/data
    restart: unless-stopped

volumes:
  prod_data:
