[project]
name = "project-slug"
version = "0.1.0"
description = "PROJECT_DESCRIPTION"
requires-python = ">=3.13"
dependencies = [
    "Django~=6.0.7",
    "django-allauth[socialaccount]~=65.18.0",
    "django-extensions==4.1",
    "django-htmx==1.27.0",
    "django-mdeditor==0.1.20",
    "django-minify-html~=1.14.0",
    "minify-html~=0.18.1",
    "django-pwa==2.0.1",
    "django-recaptcha==4.1.0",
    "django-widget-tweaks==1.5.1",
    "markdown~=3.10.2",
    "python-decouple==3.8",
    "requests~=2.34.2",
    "django-health-check~=4.4.3",
]

[dependency-groups]
dev = ["django-debug-toolbar~=7.0.0"]
prod = ["pythonanywhere-core==0.3.0"]
docker = ["gunicorn==25.3.0", "whitenoise==6.12.0"]
