#! /usr/bin/bash
set -eo pipefail

cd "$(dirname "$0")"/.. || exit 1

if [ $# -gt 0 ]; then
    uv run python manage.py test "$@" --settings=src.settings.tests
else
    uv run python manage.py test --settings=src.settings.tests
fi
